version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_USER=wisdo
      - MONGO_PASSWORD=wisdo12345
    depends_on:
      - mongodb
    networks:
      - wisdo-network

  mongodb:
    extends:
      file: docker/docker-compose.mongo.yml
      service: mongodb

networks:
  wisdo-network:
    external: true

volumes:
  mongodb-data: